from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(10, 10, 381, 31))
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.label_brand = QtWidgets.QLabel(self.centralwidget)
        self.label_brand.setGeometry(QtCore.QRect(10, 60, 101, 21))
        self.label_brand.setObjectName("label_brand")
        self.comboBox_brand = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_brand.setGeometry(QtCore.QRect(120, 60, 251, 22))
        self.comboBox_brand.setObjectName("comboBox_brand")
        self.label_model = QtWidgets.QLabel(self.centralwidget)
        self.label_model.setGeometry(QtCore.QRect(10, 100, 101, 21))
        self.label_model.setObjectName("label_model")
        self.comboBox_model = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_model.setGeometry(QtCore.QRect(120, 100, 251, 22))
        self.comboBox_model.setObjectName("comboBox_model")
        self.label_price = QtWidgets.QLabel(self.centralwidget)
        self.label_price.setGeometry(QtCore.QRect(10, 140, 101, 21))
        self.label_price.setObjectName("label_price")
        self.lineEdit_price = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_price.setGeometry(QtCore.QRect(120, 140, 251, 22))
        self.lineEdit_price.setReadOnly(True)
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.label_quantity = QtWidgets.QLabel(self.centralwidget)
        self.label_quantity.setGeometry(QtCore.QRect(10, 180, 101, 21))
        self.label_quantity.setObjectName("label_quantity")
        self.spinBox_quantity = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_quantity.setGeometry(QtCore.QRect(120, 180, 251, 22))
        self.spinBox_quantity.setMinimum(1)
        self.spinBox_quantity.setObjectName("spinBox_quantity")
        self.pushButton_buy = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_buy.setGeometry(QtCore.QRect(120, 220, 251, 31))
        self.pushButton_buy.setObjectName("pushButton_buy")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Beli Sepeda Motor"))
        self.label_title.setText(_translate("MainWindow", "Pembelian Sepeda Motor"))
        self.label_brand.setText(_translate("MainWindow", "Merek Motor:"))
        self.label_model.setText(_translate("MainWindow", "Model Motor:"))
        self.label_price.setText(_translate("MainWindow", "Harga:"))
        self.label_quantity.setText(_translate("MainWindow", "Jumlah Beli:"))
        self.pushButton_buy.setText(_translate("MainWindow", "Beli"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
