nama = input('Masukkan nama: ')
nim = input('Masukkan nim: ')
angkatan = input('Masukkan angkatan: ')
print('DATA DIRI')
print('Hallo', nama)
print('NIM mu adalah', nim)
print('Kamu adalah angkatan', angkatan)