# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'day28.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_take_number = QtWidgets.QPushButton(self.centralwidget)
        self.btn_take_number.setObjectName("btn_take_number")
        self.verticalLayout.addWidget(self.btn_take_number)
        self.lbl_queue_number = QtWidgets.QLabel(self.centralwidget)
        self.lbl_queue_number.setText("")
        self.lbl_queue_number.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_queue_number.setObjectName("lbl_queue_number")
        self.verticalLayout.addWidget(self.lbl_queue_number)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.btn_take_number.setText(_translate("MainWindow", "Ambil Nomor Antrian"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
