from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KasirWindow(object):
    def setupUi(self, KasirWindow):
        KasirWindow.setObjectName("KasirWindow")
        KasirWindow.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(KasirWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(KasirWindow)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEditNamaBarang = QtWidgets.QLineEdit(KasirWindow)
        self.lineEditNamaBarang.setObjectName("lineEditNamaBarang")
        self.verticalLayout.addWidget(self.lineEditNamaBarang)
        self.label_2 = QtWidgets.QLabel(KasirWindow)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEditHarga = QtWidgets.QLineEdit(KasirWindow)
        self.lineEditHarga.setObjectName("lineEditHarga")
        self.verticalLayout.addWidget(self.lineEditHarga)
        self.label_3 = QtWidgets.QLabel(KasirWindow)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEditJumlah = QtWidgets.QLineEdit(KasirWindow)
        self.lineEditJumlah.setObjectName("lineEditJumlah")
        self.verticalLayout.addWidget(self.lineEditJumlah)
        self.pushButtonTambah = QtWidgets.QPushButton(KasirWindow)
        self.pushButtonTambah.setObjectName("pushButtonTambah")
        self.verticalLayout.addWidget(self.pushButtonTambah)
        self.tableWidget = QtWidgets.QTableWidget(KasirWindow)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.pushButtonTotal = QtWidgets.QPushButton(KasirWindow)
        self.pushButtonTotal.setObjectName("pushButtonTotal")
        self.verticalLayout.addWidget(self.pushButtonTotal)
        self.labelTotal = QtWidgets.QLabel(KasirWindow)
        self.labelTotal.setObjectName("labelTotal")
        self.verticalLayout.addWidget(self.labelTotal)

        self.retranslateUi(KasirWindow)
        QtCore.QMetaObject.connectSlotsByName(KasirWindow)

    def retranslateUi(self, KasirWindow):
        _translate = QtCore.QCoreApplication.translate
        KasirWindow.setWindowTitle(_translate("KasirWindow", "Kasir"))
        self.label.setText(_translate("KasirWindow", "Nama Barang"))
        self.label_2.setText(_translate("KasirWindow", "Harga"))
        self.label_3.setText(_translate("KasirWindow", "Jumlah"))
        self.pushButtonTambah.setText(_translate("KasirWindow", "Tambah"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("KasirWindow", "Nama Barang"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("KasirWindow", "Harga"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("KasirWindow", "Jumlah"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("KasirWindow", "Total"))
        self.pushButtonTotal.setText(_translate("KasirWindow", "Hitung Total"))
        self.labelTotal.setText(_translate("KasirWindow", "Total: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KasirWindow = QtWidgets.QWidget()
    ui = Ui_KasirWindow()
    ui.setupUi(KasirWindow)
    KasirWindow.show()
    sys.exit(app.exec_())
